import type { Product, ProductCategory, RecommendAngle } from "./typesV2";

type ProductSeed = Omit<Product, "isCoreCampaignProduct"> & {
  isCoreCampaignProduct?: boolean;
};

function makeProduct(seed: ProductSeed): Product {
  return {
    ...seed,
    bestFoodPairings: Array.isArray(seed.bestFoodPairings) ? seed.bestFoodPairings : [],
    bestGuestPressures: Array.isArray(seed.bestGuestPressures) ? seed.bestGuestPressures : [],
    avoidWhen: Array.isArray(seed.avoidWhen) ? seed.avoidWhen : [],
    pairingTags: Array.isArray(seed.pairingTags) ? seed.pairingTags : [],
    isCoreCampaignProduct: seed.isCoreCampaignProduct !== false,
  };
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  "wine",
  "dessert_wine",
  "spirit",
  "cocktail",
  "beer",
  "dish",
  "weekly_special",
];

export const RECOMMEND_ANGLES: RecommendAngle[] = [
  "flavour",
  "story",
  "value",
  "confidence",
];

export const CORE_CAMPAIGN_PRODUCTS: Product[] = [
  makeProduct({
    id: "product_cartology_chenin",
    name: "Scroll of Cartology",
    category: "wine",
    style: "Chenin Blanc",
    varietalOrBlend: "Chenin Blanc",
    region: "Western Cape",
    price: 520,
    bottleImage: "/game/products/chenin-blanc-bottle.png",
    flavourAngle: "Dry, textured, and fresh, with enough body to feel serious.",
    storyAngle: "Made from old Cape bush vines, this shows why Chenin Blanc matters in South Africa.",
    valueAngle: "You're getting old Cape bush-vine Chenin, which gives more depth and texture than a simple white.",
    confidenceLine: "For your first South African wine, this is the bottle I'd start with.",
    recommendLines: {
      flavour: "Dry, textured, and fresh, with serious body.",
      story: "Old Cape bush vines show why Chenin matters here.",
      value: "Old-vine Chenin gives more depth than a simple white.",
      confidence: "For your first South African wine, I'd start here.",
    },
    bestFoodPairings: ["seafood", "salad", "goat_cheese"],
    bestGuestPressures: ["local_experience", "fresh_start", "safe_choice"],
    avoidWhen: ["big_red_expectation"],
    pairingTags: ["seafood", "fresh_food", "light_food"],
    introducedTier: 1,
    activeFromTier: 1,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_uva_mira_cabernet",
    name: "Scroll of Uva Mira",
    category: "wine",
    style: "Cabernet Sauvignon",
    varietalOrBlend: "Cabernet Sauvignon",
    region: "Helderberg",
    price: 780,
    bottleImage: "/game/products/cabernet-sauvignon-bottle.png",
    flavourAngle: "Full-bodied, structured, and polished, with a dry, smoky finish.",
    storyAngle: "This Cabernet comes from high Helderberg slopes, where altitude gives it structure and clarity.",
    valueAngle: "You're paying for high-altitude Helderberg fruit, which gives the wine structure and clarity.",
    confidenceLine: "If you want a serious red, this is the one I'd stand behind.",
    recommendLines: {
      flavour: "Full-bodied and polished, with a dry smoky finish.",
      story: "High Helderberg slopes give this Cabernet clarity.",
      value: "Altitude gives the wine structure and precision.",
      confidence: "If you want a serious red, I'd stand behind this.",
    },
    bestFoodPairings: ["duck", "mushroom", "chicken"],
    bestGuestPressures: ["romantic_table", "refined_choice", "status_without_weight"],
    avoidWhen: ["wants_big_structured_red"],
    pairingTags: ["duck", "mushroom", "light_red_meat"],
    introducedTier: 1,
    activeFromTier: 1,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_valmoissine_pinot_noir",
    name: "Scroll of Domaine de Valmoissine",
    category: "wine",
    style: "Pinot Noir",
    varietalOrBlend: "Pinot Noir",
    region: "South of France",
    price: 440,
    bottleImage: "/game/products/pinot-noir-bottle.png",
    flavourAngle: "Light, silky, and smooth, with soft tannins and no heavy oak.",
    storyAngle: "Louis Latour brought a Burgundian Pinot Noir style into the warmer south of France.",
    valueAngle: "You get a Burgundian-style Pinot from limestone soils, without the weight of a heavy red.",
    confidenceLine: "This keeps you in familiar red territory, just softer and more elegant.",
    recommendLines: {
      flavour: "Light, silky, and smooth, with soft tannins.",
      story: "Burgundian Pinot style from southern France.",
      value: "Limestone-soil Pinot without heavy red weight.",
      confidence: "This stays familiar, just softer and more elegant.",
    },
    bestFoodPairings: ["burger", "lamb", "chargrill"],
    bestGuestPressures: ["smart_spend", "easy_red", "group_table"],
    avoidWhen: ["wants_ultra_fine_pinot"],
    pairingTags: ["red_meat", "charred", "rich_food"],
    introducedTier: 1,
    activeFromTier: 1,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_004",
    name: "Mullineux Chenin Blanc",
    category: "wine",
    style: "Chenin Blanc",
    varietalOrBlend: "Chenin Blanc",
    region: "Swartland",
    price: 610,
    flavourAngle: "Stone fruit, texture, and a long dry finish.",
    storyAngle: "A grape and style that says South Africa confidently and intelligently.",
    valueAngle: "A strong quality jump for guests who want something with substance.",
    confidenceLine: "For a white with a bit more seriousness and texture, I'd use this.",
    bestFoodPairings: ["chicken", "pork", "creamy_dishes"],
    bestGuestPressures: ["local_experience", "wine_curiosity", "safe_step_up"],
    avoidWhen: ["wants_zingy_sauvignon_only"],
    pairingTags: ["chicken", "creamy_food", "medium_weight"],
    introducedTier: 2,
    activeFromTier: 2,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_005",
    name: "Boekenhoutskloof Syrah",
    category: "wine",
    style: "Syrah",
    varietalOrBlend: "Syrah",
    region: "Swartland",
    price: 920,
    flavourAngle: "Pepper, dark berries, and structure with lift.",
    storyAngle: "A benchmark Cape syrah that feels serious and chosen.",
    valueAngle: "A worthwhile jump when the table wants real quality rather than the cheapest red.",
    confidenceLine: "When you want the table to feel you've landed on a proper bottle, this does it.",
    bestFoodPairings: ["steak", "lamb", "game"],
    bestGuestPressures: ["confidence_test", "status_choice", "business_table"],
    avoidWhen: ["wants_light_easy_red"],
    pairingTags: ["steak", "red_meat", "structured_red"],
    introducedTier: 2,
    activeFromTier: 2,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_006",
    name: "Hamilton Russell Chardonnay",
    category: "wine",
    style: "Chardonnay",
    varietalOrBlend: "Chardonnay",
    region: "Hemel-en-Aarde",
    price: 860,
    flavourAngle: "Citrus, texture, oak detail, and calm power.",
    storyAngle: "A South African chardonnay that feels world-class without losing place.",
    valueAngle: "Premium-feeling white wine value if the table wants seriousness over novelty.",
    confidenceLine: "If the guest wants a white with class and weight, I'd confidently go here.",
    bestFoodPairings: ["fish", "lobster", "cream_sauce"],
    bestGuestPressures: ["status_choice", "precision_test", "refined_white"],
    avoidWhen: ["wants_crisp_simple_white"],
    pairingTags: ["fish", "rich_white_need", "cream_sauce"],
    introducedTier: 3,
    activeFromTier: 3,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_007",
    name: "Beaumont Mourvèdre",
    category: "wine",
    style: "Mourvèdre",
    varietalOrBlend: "Mourvèdre",
    region: "Bot River",
    price: 740,
    flavourAngle: "Savory dark fruit, earth, and a slightly wilder edge.",
    storyAngle: "A bottle for guests who want character rather than the obvious answer.",
    valueAngle: "Interesting without being the most expensive red on the page.",
    confidenceLine: "If the guest wants something distinctive but still grounded, this is smart.",
    bestFoodPairings: ["lamb", "game", "chargrill"],
    bestGuestPressures: ["collector_energy", "interesting_choice", "expertise_test"],
    avoidWhen: ["wants_soft_safe_red"],
    pairingTags: ["game", "lamb", "savory_food"],
    introducedTier: 4,
    activeFromTier: 4,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_008",
    name: "Crystallum Peter Max Pinot Noir",
    category: "wine",
    style: "Pinot Noir",
    varietalOrBlend: "Pinot Noir",
    region: "Walker Bay",
    price: 840,
    flavourAngle: "Red fruit, fine tannin, and lively perfume.",
    storyAngle: "A polished Cape pinot that feels modern, confident, and crowd-pleasing.",
    valueAngle: "A stronger premium occasion step when the table wants style with safety.",
    confidenceLine: "For a bottle that feels elevated but still easy to back, I'd choose this.",
    bestFoodPairings: ["duck", "tuna", "mushroom"],
    bestGuestPressures: ["date_night", "celebration", "taste_signal"],
    avoidWhen: ["wants_big_bold_red"],
    pairingTags: ["duck", "mushroom", "elegant_red"],
    introducedTier: 4,
    activeFromTier: 4,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_009",
    name: "Alheit Cartology",
    category: "wine",
    style: "Old Vine White Blend",
    varietalOrBlend: "Chenin Blanc Blend",
    region: "Western Cape",
    price: 980,
    flavourAngle: "Layered citrus, texture, salinity, and long finish.",
    storyAngle: "A bottle with real identity and one of the strongest Cape narratives on a list.",
    valueAngle: "High-level spend, but one that feels justified when the guest wants something meaningful.",
    confidenceLine: "If the guest wants a memorable South African white, this is an assertive answer.",
    bestFoodPairings: ["seafood", "chef_special", "complex_dishes"],
    bestGuestPressures: ["local_experience", "collector_energy", "meaningful_spend"],
    avoidWhen: ["wants_simple_glass_only"],
    pairingTags: ["seafood", "chef_special", "complex_pairing"],
    introducedTier: 5,
    activeFromTier: 5,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_010",
    name: "Kanonkop Cabernet Sauvignon",
    category: "wine",
    style: "Cabernet Sauvignon",
    varietalOrBlend: "Cabernet Sauvignon",
    region: "Stellenbosch",
    price: 1050,
    flavourAngle: "Cassis, structure, cedar, and a classic finish.",
    storyAngle: "A famous Stellenbosch cabernet that instantly signals seriousness.",
    valueAngle: "A premium spend, but one guests often recognize as worth backing.",
    confidenceLine: "If the table wants classic premium red confidence, this is a strong move.",
    bestFoodPairings: ["steak", "red_meat", "business_dinner"],
    bestGuestPressures: ["status_choice", "business_table", "classic_premium"],
    avoidWhen: ["wants_light_delicate_red"],
    pairingTags: ["steak", "red_meat", "business_table"],
    introducedTier: 5,
    activeFromTier: 5,
    activeToTier: 5,
  }),
  makeProduct({
    id: "product_dessert_001",
    name: "Klein Constantia Vin de Constance",
    category: "dessert_wine",
    style: "Natural Sweet Wine",
    varietalOrBlend: "Muscat de Frontignan",
    region: "Constantia",
    price: 220,
    flavourAngle: "Apricot, citrus peel, honey, and bright acidity.",
    storyAngle: "A historic Cape dessert wine with an instantly memorable story.",
    valueAngle: "A premium dessert finish that feels special enough to justify the upsell.",
    confidenceLine: "If you're doing a proper Cape dessert close, this is the bottle I'd point to.",
    bestFoodPairings: ["dessert"],
    bestGuestPressures: ["end_of_meal", "celebration"],
    avoidWhen: [],
    pairingTags: ["dessert", "sweet_finish"],
    introducedTier: 3,
    activeFromTier: 3,
    activeToTier: 3,
  }),
  makeProduct({
    id: "product_dessert_002",
    name: "Mullineux Straw Wine",
    category: "dessert_wine",
    style: "Straw Wine",
    varietalOrBlend: "Chenin Blanc",
    region: "Swartland",
    price: 240,
    flavourAngle: "Concentrated apricot, marmalade, and balancing acidity.",
    storyAngle: "A distinctive small-format Cape dessert close with craft appeal.",
    valueAngle: "A sharper, more modern dessert upsell for guests open to discovery.",
    confidenceLine: "For a dessert finish with personality, I'd confidently use this.",
    bestFoodPairings: ["dessert"],
    bestGuestPressures: ["end_of_meal", "discovery"],
    avoidWhen: [],
    pairingTags: ["dessert", "sweet_finish"],
    introducedTier: 4,
    activeFromTier: 4,
    activeToTier: 4,
  }),
  makeProduct({
    id: "product_spirit_001",
    name: "KWV 10 Year Brandy",
    category: "spirit",
    style: "digestif",
    varietalOrBlend: "Brandy",
    region: "Western Cape",
    price: 95,
    flavourAngle: "Warm spice, dried fruit, and a smooth finish.",
    storyAngle: "A recognisable South African after-dinner classic.",
    valueAngle: "An easy, sensible digestif upsell without overcomplicating the end of the meal.",
    confidenceLine: "If the table wants a clean after-dinner move, this is easy to stand behind.",
    bestFoodPairings: ["after_dinner"],
    bestGuestPressures: ["end_of_meal", "business_table"],
    avoidWhen: [],
    pairingTags: ["after_dinner", "digestif"],
    introducedTier: 3,
    activeFromTier: 3,
    activeToTier: 3,
  }),
  makeProduct({
    id: "product_spirit_002",
    name: "Amarula Reserve",
    category: "spirit",
    style: "digestif",
    varietalOrBlend: "Cream Liqueur",
    region: "South Africa",
    price: 88,
    flavourAngle: "Creamy caramel, vanilla, and an easy sweet finish.",
    storyAngle: "A recognisable South African after-dinner option with local identity.",
    valueAngle: "A softer, accessible second-sale option at the end of the meal.",
    confidenceLine: "If the table wants a relaxed after-dinner finish, this is easy to recommend.",
    bestFoodPairings: ["after_dinner", "dessert"],
    bestGuestPressures: ["end_of_meal", "celebration"],
    avoidWhen: [],
    pairingTags: ["after_dinner", "dessert"],
    introducedTier: 4,
    activeFromTier: 4,
    activeToTier: 4,
  }),
];

export function isV1PlayableCategory(category: ProductCategory): boolean {
  return category === "wine" || category === "dessert_wine" || category === "spirit";
}

export function getCoreCampaignProducts(): Product[] {
  return CORE_CAMPAIGN_PRODUCTS.slice();
}

export function getProductsByCategory(
  products: Product[],
  category: ProductCategory,
): Product[] {
  return (Array.isArray(products) ? products : []).filter((product) => product.category === category);
}

export function getProductById(
  products: Product[],
  productId: string | null | undefined,
): Product | null {
  if (!productId) return null;
  return (Array.isArray(products) ? products : []).find((product) => product.id === productId) || null;
}
