import type {
  GuestReviewProfile,
  ScenarioWineCandidate,
  TableServiceScenario,
  WineEncounterVariant,
} from "./types";

function review(
  partial: GuestReviewProfile,
): GuestReviewProfile {
  return partial;
}

function variant(
  partial: WineEncounterVariant,
): WineEncounterVariant {
  return partial;
}

const SLOW_STEAK_CANDIDATES: ScenarioWineCandidate[] = [
  {
    productId: "product_uva_mira_cabernet",
    commercialRole: "premium",
    matchRating: "strong",
    foodCompatibility: "strong",
    guestCompatibility: "strong",
    priceCompatibility: "risky",
    maxApModifier: 0,
    startingMoodDelta: 0,
    startingProgressDelta: 0,
    startingFrustrationDelta: 1,
    encounterVariantId: "slow_couple_premium_red",
    guestOpeningLine:
      "That looks like a serious bottle. What makes it worth the price?",
    guestProductConcern: "price",
    preferredRecommendAngles: ["value", "story"],
    acceptableRecommendAngles: ["flavour", "confidence"],
    weakRecommendAngles: ["confidence"],
    resistanceLevel: "high",
  },
  {
    productId: "product_valmoissine_pinot_noir",
    commercialRole: "safe",
    matchRating: "strong",
    foodCompatibility: "strong",
    guestCompatibility: "strong",
    priceCompatibility: "strong",
    maxApModifier: 0,
    startingMoodDelta: 1,
    startingProgressDelta: 1,
    startingFrustrationDelta: 0,
    encounterVariantId: "slow_couple_safe_pinot",
    guestOpeningLine: "That sounds like something we would normally enjoy.",
    preferredRecommendAngles: ["flavour", "confidence"],
    acceptableRecommendAngles: ["story", "value"],
    weakRecommendAngles: ["value"],
    resistanceLevel: "low",
  },
  {
    productId: "product_007",
    commercialRole: "partner",
    matchRating: "acceptable",
    foodCompatibility: "strong",
    guestCompatibility: "acceptable",
    priceCompatibility: "strong",
    maxApModifier: 0,
    startingMoodDelta: 0,
    startingProgressDelta: 0,
    startingFrustrationDelta: 0,
    encounterVariantId: "slow_couple_partner_mourvedre",
    guestOpeningLine: "We do not know that producer. What is the wine like?",
    preferredRecommendAngles: ["story", "flavour"],
    acceptableRecommendAngles: ["confidence"],
    weakRecommendAngles: ["value"],
    resistanceLevel: "medium",
  },
];

const REGULAR_FISH_CANDIDATES: ScenarioWineCandidate[] = [
  {
    productId: "product_006",
    commercialRole: "premium",
    matchRating: "acceptable",
    foodCompatibility: "strong",
    guestCompatibility: "acceptable",
    priceCompatibility: "risky",
    maxApModifier: 0,
    startingMoodDelta: 0,
    startingProgressDelta: 0,
    startingFrustrationDelta: 1,
    encounterVariantId: "regular_fish_premium_chardonnay",
    guestOpeningLine: "Is that not a bit rich for the fish?",
    guestProductConcern: "richness",
    preferredRecommendAngles: ["flavour", "value"],
    acceptableRecommendAngles: ["story"],
    weakRecommendAngles: ["confidence"],
    resistanceLevel: "high",
  },
  {
    productId: "product_coastal_sauvignon",
    commercialRole: "safe",
    matchRating: "strong",
    foodCompatibility: "strong",
    guestCompatibility: "strong",
    priceCompatibility: "strong",
    maxApModifier: 0,
    startingMoodDelta: 1,
    startingProgressDelta: 1,
    startingFrustrationDelta: 0,
    encounterVariantId: "regular_fish_safe_sauvignon",
    guestOpeningLine: "Fresh and local — that is closer to what I expect.",
    preferredRecommendAngles: ["confidence", "flavour"],
    acceptableRecommendAngles: ["value"],
    weakRecommendAngles: ["story"],
    resistanceLevel: "low",
  },
  {
    productId: "product_cartology_chenin",
    commercialRole: "partner",
    matchRating: "strong",
    foodCompatibility: "strong",
    guestCompatibility: "strong",
    priceCompatibility: "strong",
    maxApModifier: 0,
    startingMoodDelta: 0,
    startingProgressDelta: 0,
    startingFrustrationDelta: 0,
    encounterVariantId: "regular_fish_partner_chenin",
    guestOpeningLine: "Chenin can work. Why this one with the fish?",
    preferredRecommendAngles: ["story", "flavour"],
    acceptableRecommendAngles: ["confidence"],
    weakRecommendAngles: ["value"],
    resistanceLevel: "medium",
  },
];

export const TABLE_SERVICE_SCENARIOS: Record<string, TableServiceScenario> = {
  slow_steak_couple: {
    id: "slow_steak_couple",
    guestId: "blonde_date",
    secondWineOpportunityAllowed: true,
    review: review({
      scenarioId: "slow_steak_couple",
      guestId: "blonde_date",
      guestType: "tourist",
      pace: "relaxed",
      familiarity: "new",
      discoveryNeed: "medium",
      knownFoodIntent: "steak",
      knownFoodCategory: "red_meat",
      knownOccasion: "date",
      knownBudgetSignal: "medium",
      reviewClues: [
        "They appear relaxed and settled in.",
        "They are taking time over the menu.",
        "They seem interested in the steak selection.",
        "They do not appear to be in a hurry.",
      ],
      preferredGreetingRoutes: ["aperitif"],
      acceptableGreetingRoutes: ["wine", "food"],
      weakGreetingRoutes: [],
      usefulWineStyles: ["cabernet", "pinot", "structured_red"],
      unsuitableWineStyles: ["heavy_oak_white", "dessert"],
      encounterTraits: {
        askTolerance: "medium",
        recommendationTolerance: "high",
        commitReadiness: "normal",
        pressureSensitivity: "medium",
      },
    }),
    wineCandidates: SLOW_STEAK_CANDIDATES,
    variants: {
      slow_couple_premium_red: variant({
        id: "slow_couple_premium_red",
        productId: "product_uva_mira_cabernet",
        guestOpeningLine:
          "That looks like a serious bottle. What makes it worth the price?",
        guestProductConcern: "price",
        preferredRecommendAngles: ["value", "story"],
        acceptableRecommendAngles: ["flavour", "confidence"],
        weakRecommendAngles: ["confidence"],
        resistanceLevel: "high",
        successResponse: "Alright — if it carries the steak, we will take it.",
        weakSuccessResponse: "We will try it, but keep the pour measured.",
        failureResponse: "Too much for tonight. Leave the list with us.",
      }),
      slow_couple_safe_pinot: variant({
        id: "slow_couple_safe_pinot",
        productId: "product_valmoissine_pinot_noir",
        guestOpeningLine: "That sounds like something we would normally enjoy.",
        preferredRecommendAngles: ["flavour", "confidence"],
        acceptableRecommendAngles: ["story", "value"],
        weakRecommendAngles: ["value"],
        resistanceLevel: "low",
        successResponse: "Perfect. That fits the pace of the night.",
        weakSuccessResponse: "Fine — that will do.",
        failureResponse: "Maybe we should wait until after the food.",
      }),
      slow_couple_partner_mourvedre: variant({
        id: "slow_couple_partner_mourvedre",
        productId: "product_007",
        guestOpeningLine: "We do not know that producer. What is the wine like?",
        preferredRecommendAngles: ["story", "flavour"],
        acceptableRecommendAngles: ["confidence"],
        weakRecommendAngles: ["value"],
        resistanceLevel: "medium",
        successResponse: "Interesting — we will try it with the steak.",
        weakSuccessResponse: "Alright, one bottle while we decide the rest.",
        failureResponse: "Too unfamiliar for tonight.",
      }),
    },
  },

  regular_fish_guest: {
    id: "regular_fish_guest",
    guestId: "african_older_gentleman",
    secondWineOpportunityAllowed: true,
    review: review({
      scenarioId: "regular_fish_guest",
      guestId: "african_older_gentleman",
      guestType: "regular",
      pace: "direct",
      familiarity: "regular",
      discoveryNeed: "low",
      knownFoodIntent: "fish",
      knownFoodCategory: "seafood",
      knownOccasion: "habitual",
      knownBudgetSignal: "medium",
      reviewClues: [
        "This guest visits regularly.",
        "They usually order the same fish dish.",
        "They know the menu well.",
        "They prefer confident, efficient service.",
      ],
      preferredGreetingRoutes: ["wine"],
      acceptableGreetingRoutes: ["aperitif"],
      weakGreetingRoutes: ["food"],
      usefulWineStyles: ["sauvignon", "chenin", "chardonnay", "white"],
      unsuitableWineStyles: ["heavy_cabernet", "dessert"],
      encounterTraits: {
        askTolerance: "low",
        recommendationTolerance: "high",
        commitReadiness: "early",
        pressureSensitivity: "high",
      },
    }),
    wineCandidates: REGULAR_FISH_CANDIDATES,
    variants: {
      regular_fish_premium_chardonnay: variant({
        id: "regular_fish_premium_chardonnay",
        productId: "product_006",
        guestOpeningLine: "Is that not a bit rich for the fish?",
        guestProductConcern: "richness",
        preferredRecommendAngles: ["flavour", "value"],
        acceptableRecommendAngles: ["story"],
        weakRecommendAngles: ["confidence"],
        resistanceLevel: "high",
        successResponse: "If it stays precise with the fish, fine.",
        weakSuccessResponse: "One glass first — then we will see.",
        failureResponse: "Too heavy. Bring what I usually drink.",
      }),
      regular_fish_safe_sauvignon: variant({
        id: "regular_fish_safe_sauvignon",
        productId: "product_coastal_sauvignon",
        guestOpeningLine: "Fresh and local — that is closer to what I expect.",
        preferredRecommendAngles: ["confidence", "flavour"],
        acceptableRecommendAngles: ["value"],
        weakRecommendAngles: ["story"],
        resistanceLevel: "low",
        successResponse: "Yes. That is the lane. Pour it.",
        weakSuccessResponse: "Fine. Keep it moving.",
        failureResponse: "Not tonight.",
      }),
      regular_fish_partner_chenin: variant({
        id: "regular_fish_partner_chenin",
        productId: "product_cartology_chenin",
        guestOpeningLine: "Chenin can work. Why this one with the fish?",
        preferredRecommendAngles: ["story", "flavour"],
        acceptableRecommendAngles: ["confidence"],
        weakRecommendAngles: ["value"],
        resistanceLevel: "medium",
        successResponse: "Alright — that explanation holds.",
        weakSuccessResponse: "Acceptable. Do not oversell it.",
        failureResponse: "Too much story for a regular table.",
      }),
    },
  },

  regular_fish_couple: {
    id: "regular_fish_couple",
    guestId: "african_regular_table",
    secondWineOpportunityAllowed: true,
    review: review({
      scenarioId: "regular_fish_couple",
      guestId: "african_regular_table",
      guestType: "regular",
      pace: "direct",
      familiarity: "regular",
      discoveryNeed: "low",
      knownFoodIntent: "fish",
      knownFoodCategory: "seafood",
      knownOccasion: "habitual",
      knownBudgetSignal: "medium",
      reviewClues: [
        "This couple visits regularly.",
        "They usually share the fish.",
        "They know the menu and the room.",
        "They prefer confident, efficient service.",
      ],
      preferredGreetingRoutes: ["wine"],
      acceptableGreetingRoutes: ["aperitif"],
      weakGreetingRoutes: ["food"],
      usefulWineStyles: ["sauvignon", "chenin", "chardonnay", "white"],
      unsuitableWineStyles: ["heavy_cabernet"],
      encounterTraits: {
        askTolerance: "low",
        recommendationTolerance: "high",
        commitReadiness: "early",
        pressureSensitivity: "high",
      },
    }),
    wineCandidates: REGULAR_FISH_CANDIDATES.map((candidate) => ({
      ...candidate,
      encounterVariantId: candidate.encounterVariantId.replace(
        "regular_fish_",
        "regular_fish_couple_",
      ),
    })),
    variants: {},
  },

  skeptic_reader_table: {
    id: "skeptic_reader_table",
    guestId: "skeptic_reader",
    secondWineOpportunityAllowed: false,
    review: review({
      scenarioId: "skeptic_reader_table",
      guestId: "skeptic_reader",
      guestType: "skeptic",
      pace: "cautious",
      familiarity: "somewhat_familiar",
      discoveryNeed: "high",
      knownFoodIntent: undefined,
      knownBudgetSignal: "unknown",
      reviewClues: [
        "They watch the room more than the menu.",
        "They seem ready to test one precise reason.",
        "They do not look hurried.",
        "A soft sell will not earn trust here.",
      ],
      preferredGreetingRoutes: ["wine"],
      acceptableGreetingRoutes: ["food"],
      weakGreetingRoutes: ["aperitif"],
      usefulWineStyles: ["cabernet", "structured_red"],
      unsuitableWineStyles: ["rose"],
      encounterTraits: {
        askTolerance: "medium",
        recommendationTolerance: "medium",
        commitReadiness: "late",
        pressureSensitivity: "high",
      },
    }),
    wineCandidates: [
      {
        productId: "product_uva_mira_cabernet",
        commercialRole: "premium",
        matchRating: "strong",
        foodCompatibility: "acceptable",
        guestCompatibility: "strong",
        priceCompatibility: "risky",
        maxApModifier: 0,
        startingMoodDelta: 0,
        startingProgressDelta: 0,
        startingFrustrationDelta: 1,
        encounterVariantId: "skeptic_premium_cabernet",
        guestOpeningLine: "One clear reason — not a speech.",
        preferredRecommendAngles: ["value", "confidence"],
        resistanceLevel: "high",
      },
      {
        productId: "product_valmoissine_pinot_noir",
        commercialRole: "safe",
        matchRating: "acceptable",
        foodCompatibility: "acceptable",
        guestCompatibility: "acceptable",
        priceCompatibility: "strong",
        maxApModifier: 0,
        startingMoodDelta: 0,
        startingProgressDelta: 0,
        startingFrustrationDelta: 0,
        encounterVariantId: "skeptic_safe_pinot",
        guestOpeningLine: "Is that precise enough, or just easy?",
        preferredRecommendAngles: ["flavour", "confidence"],
        resistanceLevel: "medium",
      },
      {
        productId: "product_coastal_sauvignon",
        commercialRole: "partner",
        matchRating: "poor",
        foodCompatibility: "poor",
        guestCompatibility: "poor",
        priceCompatibility: "strong",
        maxApModifier: -5,
        startingMoodDelta: -1,
        startingProgressDelta: -1,
        startingFrustrationDelta: 2,
        encounterVariantId: "skeptic_partner_sauvignon",
        guestOpeningLine: "That does not fit this table.",
        preferredRecommendAngles: ["story"],
        resistanceLevel: "high",
      },
    ],
    variants: {},
  },

  skeptic_v1_table: {
    id: "skeptic_v1_table",
    guestId: "skeptic_v1",
    secondWineOpportunityAllowed: false,
    review: review({
      scenarioId: "skeptic_v1_table",
      guestId: "skeptic_v1",
      guestType: "skeptic",
      pace: "cautious",
      familiarity: "somewhat_familiar",
      discoveryNeed: "high",
      reviewClues: [
        "Precision matters more than warmth here.",
        "They look ready to reject a vague pitch.",
        "They are not browsing for entertainment.",
        "One relevant reason will go further than three.",
      ],
      preferredGreetingRoutes: ["wine"],
      acceptableGreetingRoutes: ["food"],
      weakGreetingRoutes: ["aperitif"],
      usefulWineStyles: ["cabernet", "structured_red"],
      unsuitableWineStyles: ["rose"],
      encounterTraits: {
        askTolerance: "low",
        recommendationTolerance: "medium",
        commitReadiness: "late",
        pressureSensitivity: "high",
      },
    }),
    wineCandidates: [
      {
        productId: "product_uva_mira_cabernet",
        commercialRole: "premium",
        matchRating: "strong",
        foodCompatibility: "acceptable",
        guestCompatibility: "strong",
        priceCompatibility: "risky",
        maxApModifier: 0,
        startingMoodDelta: 0,
        startingProgressDelta: 0,
        startingFrustrationDelta: 1,
        encounterVariantId: "skeptic_v1_premium_cabernet",
        preferredRecommendAngles: ["value", "confidence"],
        resistanceLevel: "high",
      },
      {
        productId: "product_valmoissine_pinot_noir",
        commercialRole: "safe",
        matchRating: "acceptable",
        foodCompatibility: "acceptable",
        guestCompatibility: "acceptable",
        priceCompatibility: "strong",
        maxApModifier: 0,
        startingMoodDelta: 0,
        startingProgressDelta: 0,
        startingFrustrationDelta: 0,
        encounterVariantId: "skeptic_v1_safe_pinot",
        preferredRecommendAngles: ["flavour", "confidence"],
        resistanceLevel: "medium",
      },
      {
        productId: "product_cape_rose",
        commercialRole: "partner",
        matchRating: "poor",
        foodCompatibility: "poor",
        guestCompatibility: "poor",
        priceCompatibility: "strong",
        maxApModifier: -5,
        startingMoodDelta: -1,
        startingProgressDelta: -1,
        startingFrustrationDelta: 2,
        encounterVariantId: "skeptic_v1_partner_rose",
        preferredRecommendAngles: ["story"],
        resistanceLevel: "high",
      },
    ],
    variants: {},
  },
};

const GUEST_TO_SCENARIO: Record<string, string> = {
  blonde_date: "slow_steak_couple",
  african_older_gentleman: "regular_fish_guest",
  african_regular_table: "regular_fish_couple",
  skeptic_reader: "skeptic_reader_table",
  skeptic_v1: "skeptic_v1_table",
};

export function getScenarioForGuest(
  guestId: string | null | undefined,
): TableServiceScenario | null {
  const id = String(guestId || "").trim();
  if (!id) return null;
  const scenarioId = GUEST_TO_SCENARIO[id];
  if (!scenarioId) return null;
  const scenario = TABLE_SERVICE_SCENARIOS[scenarioId];
  if (!scenario) return null;
  // Couple fish reuses fish variants with renamed ids.
  if (scenario.id === "regular_fish_couple" && Object.keys(scenario.variants).length === 0) {
    const base = TABLE_SERVICE_SCENARIOS.regular_fish_guest;
    const variants: TableServiceScenario["variants"] = {};
    for (const candidate of scenario.wineCandidates) {
      const sourceId = candidate.encounterVariantId.replace(
        "regular_fish_couple_",
        "regular_fish_",
      );
      const source = base.variants[sourceId];
      if (source) {
        variants[candidate.encounterVariantId] = {
          ...source,
          id: candidate.encounterVariantId,
        };
      }
    }
    return { ...scenario, variants };
  }
  return scenario;
}
